### ISSUE TITLE
conjuntos, funciones y relaciones 

### ISSUE THREAD

**Issue by NBbrook** [SistemasTecTlaxiaco/actividad-4-mapa-mental-NBbrook#2]
[conjuntos, funciones y relaciones .pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-NBbrook/files/12673545/conjuntos.funciones.y.relaciones.pdf)

**Comment by elisa1223** [comment]
Manejo conceptual y dominio del tema 25%
Relacion entre los conceptos incluidos en el mapa 25%
Calidad de la presentación 25%
Jerarquía 25%

Calificación 20 / 20
Evaluado por el quipo de Elisa Sánchez Coronel

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
